-- 0037_seed_channel_field_rules.sql
-- Seed which fields each sales channel pushes / requires (docs/tiktok-readiness-spec.md 2.4).
-- shopify_komputerzz rows MIRROR CURRENT behaviour (so a later push rewire cannot regress it).
-- shopify_tiktok rows are the TARGET set. Inert until the push code reads this table.
DELETE FROM channel_field_rules WHERE platform IN ('shopify_komputerzz','shopify_tiktok');
INSERT INTO channel_field_rules (platform, field_key, pushed, required, notes) VALUES
  ('shopify_komputerzz','title',1,0,NULL),
  ('shopify_komputerzz','description',1,0,NULL),
  ('shopify_komputerzz','meta_description',1,0,NULL),
  ('shopify_komputerzz','status',1,0,NULL),
  ('shopify_komputerzz','price',1,0,NULL),
  ('shopify_komputerzz','compare_at',1,0,NULL),
  ('shopify_komputerzz','ean',1,0,NULL),
  ('shopify_komputerzz','vendor',1,0,NULL),
  ('shopify_komputerzz','product_type',1,0,NULL),
  ('shopify_komputerzz','variants',1,0,NULL),
  ('shopify_komputerzz','images',1,0,NULL),
  ('shopify_komputerzz','category',1,0,'resolves to root ''el'' today (no channel_category_map rows for komputerzz)'),
  ('shopify_komputerzz','attributes',1,0,NULL),
  ('shopify_komputerzz','collections',1,0,NULL),
  ('shopify_komputerzz','translations',1,0,NULL),
  ('shopify_komputerzz','collection_attribute_values',1,0,NULL),
  ('shopify_komputerzz','package_dims',0,0,NULL),
  ('shopify_komputerzz','package_weight',0,0,'weight not pushed to komputerzz today'),
  ('shopify_komputerzz','gpsr',0,0,NULL),
  ('shopify_komputerzz','warranty',0,0,NULL),
  ('shopify_komputerzz','box_contents',0,0,NULL),
  ('shopify_tiktok','title',1,1,NULL),
  ('shopify_tiktok','description',1,1,NULL),
  ('shopify_tiktok','meta_description',1,0,NULL),
  ('shopify_tiktok','status',1,0,NULL),
  ('shopify_tiktok','price',1,1,NULL),
  ('shopify_tiktok','compare_at',1,0,NULL),
  ('shopify_tiktok','ean',1,1,NULL),
  ('shopify_tiktok','vendor',1,0,NULL),
  ('shopify_tiktok','product_type',1,0,NULL),
  ('shopify_tiktok','variants',1,0,NULL),
  ('shopify_tiktok','images',1,1,'>=5 compliant (see tiktok image policy / readiness gate)'),
  ('shopify_tiktok','category',1,1,'granular, resolved from channel_category_map'),
  ('shopify_tiktok','attributes',1,1,'normalized, mapped to TikTok category attributes in the native app'),
  ('shopify_tiktok','collections',0,0,NULL),
  ('shopify_tiktok','translations',0,0,NULL),
  ('shopify_tiktok','collection_attribute_values',0,0,NULL),
  ('shopify_tiktok','package_dims',1,1,NULL),
  ('shopify_tiktok','package_weight',1,1,NULL),
  ('shopify_tiktok','gpsr',1,1,NULL),
  ('shopify_tiktok','warranty',1,0,NULL),
  ('shopify_tiktok','box_contents',1,0,NULL);
