-- 0039_seed_channel_category_map_full.sql
-- Full collection -> Shopify Standard Product Taxonomy map for BOTH Shopify channels
-- (docs/tiktok-readiness-spec.md §2.3). Unifies Komputerzz + Tech Store on one product
-- category layer; TikTok derives its category from it via the native app.
-- Replaces the initial 6-row tiktok-only seed (0038). GIDs verified 2026-07-28.
-- NOTE: category is set only on NEW-product creation, so this recategorises FUTURE
-- products only; existing live listings are untouched until re-created.
DELETE FROM channel_category_map;
-- taxonomy_key -> category: ai_workstations=Desktop Computers; accessories=Computer Accessories; audio=Audio Components; cameras=Cameras; connectivity=Networking; controllers=Game Controllers; desktops=Desktop Computers; docking_stations=Laptop Docking Stations; electric_scooters=E-Scooters; foldable_monitors=Computer Monitors; gaming_chairs=Gaming Chairs; gaming_consoles=Video Game Consoles; gaming_desks=Desks; gaming_laptops=Gaming Laptops; gaming_monitors=Computer Monitors; graphics_cards=Video Cards & Adapters; headsets_earbuds=Headphones & Headsets; keyboards=Keyboards; laptop_bags=Laptop Bags; laptops=Laptops; mice=Mice & Trackballs; monitors=Computer Monitors; projectors=Projectors; storage=Storage Devices; tablets=Tablet Computers; ultrawide_monitors=Computer Monitors; webcams=Webcams; work_laptops=Laptops
INSERT INTO channel_category_map (taxonomy_key, platform, shopify_category_gid, tiktok_category_id, required_attribute_keys) VALUES
  ('ai_workstations','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-3',NULL,NULL),
  ('accessories','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-8',NULL,NULL),
  ('audio','shopify_tiktok','gid://shopify/TaxonomyCategory/el-2-2',NULL,NULL),
  ('cameras','shopify_tiktok','gid://shopify/TaxonomyCategory/co-2',NULL,NULL),
  ('connectivity','shopify_tiktok','gid://shopify/TaxonomyCategory/el-12',NULL,NULL),
  ('controllers','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-9-12-5',NULL,NULL),
  ('desktops','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-3',NULL,NULL),
  ('docking_stations','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-8-7',NULL,NULL),
  ('electric_scooters','shopify_tiktok','gid://shopify/TaxonomyCategory/sg-4-15-1',NULL,NULL),
  ('foldable_monitors','shopify_tiktok','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('gaming_chairs','shopify_tiktok','gid://shopify/TaxonomyCategory/fr-7-7',NULL,NULL),
  ('gaming_consoles','shopify_tiktok','gid://shopify/TaxonomyCategory/el-19',NULL,NULL),
  ('gaming_desks','shopify_tiktok','gid://shopify/TaxonomyCategory/fr-12-1',NULL,NULL),
  ('gaming_laptops','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-11-2',NULL,NULL),
  ('gaming_monitors','shopify_tiktok','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('graphics_cards','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-9-10-5',NULL,NULL),
  ('headsets_earbuds','shopify_tiktok','gid://shopify/TaxonomyCategory/el-2-2-7',NULL,NULL),
  ('keyboards','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-9-12-8',NULL,NULL),
  ('laptop_bags','shopify_tiktok','gid://shopify/TaxonomyCategory/lb-15',NULL,NULL),
  ('laptops','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-6',NULL,NULL),
  ('mice','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-9-12-11',NULL,NULL),
  ('monitors','shopify_tiktok','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('projectors','shopify_tiktok','gid://shopify/TaxonomyCategory/el-17-2',NULL,NULL),
  ('storage','shopify_tiktok','gid://shopify/TaxonomyCategory/el-7-9-14',NULL,NULL),
  ('tablets','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-8',NULL,NULL),
  ('ultrawide_monitors','shopify_tiktok','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('webcams','shopify_tiktok','gid://shopify/TaxonomyCategory/co-2-8',NULL,NULL),
  ('work_laptops','shopify_tiktok','gid://shopify/TaxonomyCategory/el-6-6',NULL,NULL),
  ('ai_workstations','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-3',NULL,NULL),
  ('accessories','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-8',NULL,NULL),
  ('audio','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-2-2',NULL,NULL),
  ('cameras','shopify_komputerzz','gid://shopify/TaxonomyCategory/co-2',NULL,NULL),
  ('connectivity','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-12',NULL,NULL),
  ('controllers','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-9-12-5',NULL,NULL),
  ('desktops','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-3',NULL,NULL),
  ('docking_stations','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-8-7',NULL,NULL),
  ('electric_scooters','shopify_komputerzz','gid://shopify/TaxonomyCategory/sg-4-15-1',NULL,NULL),
  ('foldable_monitors','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('gaming_chairs','shopify_komputerzz','gid://shopify/TaxonomyCategory/fr-7-7',NULL,NULL),
  ('gaming_consoles','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-19',NULL,NULL),
  ('gaming_desks','shopify_komputerzz','gid://shopify/TaxonomyCategory/fr-12-1',NULL,NULL),
  ('gaming_laptops','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-11-2',NULL,NULL),
  ('gaming_monitors','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('graphics_cards','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-9-10-5',NULL,NULL),
  ('headsets_earbuds','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-2-2-7',NULL,NULL),
  ('keyboards','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-9-12-8',NULL,NULL),
  ('laptop_bags','shopify_komputerzz','gid://shopify/TaxonomyCategory/lb-15',NULL,NULL),
  ('laptops','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-6',NULL,NULL),
  ('mice','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-9-12-11',NULL,NULL),
  ('monitors','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('projectors','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-17-2',NULL,NULL),
  ('storage','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-7-9-14',NULL,NULL),
  ('tablets','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-8',NULL,NULL),
  ('ultrawide_monitors','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-17-1',NULL,NULL),
  ('webcams','shopify_komputerzz','gid://shopify/TaxonomyCategory/co-2-8',NULL,NULL),
  ('work_laptops','shopify_komputerzz','gid://shopify/TaxonomyCategory/el-6-6',NULL,NULL);
