export type AttributeCollection =
  | 'laptops'
  | 'monitor'
  | 'mice'
  | 'laptop_bags'
  | 'headsets'
  | 'keyboards'
  | 'controllers'
  | 'docking_stations'
  | 'connectivity'
  | 'storage'
  | 'graphics_cards'
  | 'projectors'
  | 'audio'
  | 'cameras'
  | 'electric_scooters'
  | 'gaming_chairs'
  | 'gaming_consoles'
  | 'gaming_desks'
  | 'webcams'
  | 'ai_workstations'
  | 'desktops'
export type AttributeBrand = 'acer' | 'predator'

type AttributeOptionsMap = Record<string, string[]>

export const ATTRIBUTE_OPTIONS: Record<AttributeCollection, AttributeOptionsMap> = {
  laptops: {
    brand: ['Acer', 'Predator'],
    model: ['Aspire 3', 'Aspire 5', 'Swift Go 14', 'Swift X 14', 'TM P4', 'Extensa 15', 'Nitro V 15', 'Nitro 16', 'HeliosNeo16', 'Helios 16', 'Triton 14'],
    category: ['Ultrabook', 'Gaming', 'Business', 'Creator', 'Everyday', '2-in-1'],
    series: ['Aspire', 'Swift', 'Nitro', 'Helios', 'Triton', 'TM', 'Extensa'],
    screen_size: ['13.3', '14', '15.6', '16', '17.3', '18'],
    resolution: ['1920x1080', '1920x1200', '2560x1600', '2880x1800', '3840x2160', '8K@60Hz'],
    processor: ['Core i5', 'Core i7', 'Core i9', 'Core U7', 'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9'],
    screen_type: ['IPS', 'OLED', 'Mini LED'],
    refresh_rate: ['60', '90', '120', '144', '165', '240'],
    touchscreen: ['No', 'Yes'],
    processor_brand: ['Intel', 'AMD', 'Qualcomm'],
    processor_model: ['Core i5', 'Core i7', 'Core i9', 'Core U5', 'Core U7', 'Core U9', 'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9', 'SD X Elite'],
    processor_generation: ['12th Gen', '13th Gen', '14th Gen', 'Core U S1', 'Core U S2', 'Ryzen 7000', 'Ryzen 8000', 'Ryzen 9000'],
    processor_cores: ['6', '8', '10', '12', '14', '16', '24'],
    gpu_brand: ['NVIDIA', 'AMD', 'Intel'],
    gpu: ['Intel Arc', 'RTX 4050', 'RTX 4060', 'RTX 4070', 'RTX 4080', 'RTX 4090'],
    ram: ['8', '16', '32', '64'],
    ram_type: ['DDR4', 'DDR5', 'LPDDR5', 'LPDDR5X'],
    ram_max: ['16', '32', '64', '96'],
    storage_type: ['NVMe SSD', 'SATA SSD', 'NVMe 4.0', 'NVMe 5.0', 'PCIe 4.0'],
    storage: ['256GB SSD', '512GB SSD', '1TB SSD', '2TB SSD', '4TB SSD'],
    battery_life: ['6', '8', '10', '12', '14'],
    weight: ['<1.4', '1.4-1.8', '1.8-2.3', '>2.3'],
    wifi: ['Wi-Fi 6', 'Wi-Fi 6E', 'Wi-Fi 7'],
    bluetooth: ['5.1', '5.2', '5.3', '5.4'],
    ports: ['USB-A', 'USB-C', 'TB4', 'HDMI 2.1', 'microSD', '3.5mm Jack', 'RJ45'],
    operating_system: ['Win 11 Home', 'Win 11 Pro', 'Linux', 'No OS'],
    color: ['Black', 'White', 'Silver', 'Blue', 'Gray'],
  },
  monitor: {
    brand: ['Acer', 'Predator'],
    model: ['Nitro KG241Y', 'Nitro XV272U', 'Acer CB272', 'XB273K', 'X34 V', 'Predator X45'],
    category: ['Gaming', 'Office', 'Creator', 'Ultrawide', 'Portable', 'Foldable', '3D'],
    product_subtype: ['Monitor', 'Gaming monitor', 'Curved monitor', 'Portable monitor', 'Foldable monitor', '3D monitor'],
    series: ['Nitro', 'Acer CB', 'Predator XB', 'Predator X'],
    screen_size: ['15.6', '18.5', '23.8', '24', '26.5', '27', '31.5', '34', '45', '57.1'],
    resolution: ['1920x1080', '2560x1440', '3440x1440', '3840x2160', '7680x2160'],
    screen_resolution: ['1920x1080', '2560x1440', '3440x1440', '3840x2160', '7680x2160'],
    panel_type: ['IPS', 'IPS Matte', 'IPS Glare', 'VA', 'TN Matte', 'OLED', 'Mini LED', 'Glare', 'AHVA'],
    screen_type: ['IPS', 'VA', 'OLED', 'Mini LED'],
    refresh_rate: ['60', '75', '100', '120', '144', '160', '165', '175', '180', '240', '500', 'Vert Freq'],
    response_time: ['0.03', '0.1', '0.5', '1', '2', '4', '5', '8'],
    aspect_ratio: ['16:9', '16:10', '21:9', '32:9'],
    curved: ['No', '1000R', '1500R', '1800R', '3800R'],
    brightness: ['250', '300', '350', '400', '600', '1000'],
    contrast_ratio: ['1000:1', '3000:1', '1000000:1'],
    hdr: ['None', 'HDR10', 'HDR400', 'HDR500', 'HDR600', 'HDR1000'],
    gsync_freesync: ['None', 'G-SYNC Comp', 'G-SYNC', 'FreeSync', 'FS Premium', 'FS Prem Pro'],
    color_gamut: ['95% sRGB', '99% sRGB', '95% DCI-P3', '99% Adobe'],
    ports: ['HDMI 2.0', 'HDMI 2.1', 'DP 1.4', 'USB-C', 'USB Hub', '3.5mm Out', 'VGA'],
    vesa_mount: ['75x75', '100x100'],
    color: ['Black', 'White', 'Silver'],
  },
  mice: {
    product_subtype: ['Mouse', 'Gaming mouse', 'Vertical mouse', 'Keyboard and mouse combo', 'Mousepad'],
    dpi: ['1600', '7200', '16000', '19000'],
    sensor: ['Optical', 'PixArt 3370', 'PixArt 3389'],
    buttons: ['3', '6', '10'],
    connection: ['Wired USB', '2.4GHz Wireless', 'Bluetooth 5.0', '2.4GHz Wireless + Bluetooth 5.0'],
    polling_rate: ['125Hz', '2000Hz'],
    response_time: ['1ms'],
    ips: ['400 IPS'],
    lighting: ['RGB', '7-color lighting', '16.8M RGB'],
    scroll: ['Hyper-fast infinite scroll'],
    hand_orientation: ['Right-handed'],
    battery: ['2 x AAA', 'Rechargeable'],
    battery_life: ['Up to 120 hours'],
    charging_time: ['3 hours'],
    charging_cable: ['Micro-USB'],
    receiver: ['USB receiver', 'USB Nano receiver'],
    keyboard_shortcuts: ['11 shortcuts'],
    keystroke_life: ['5 million keystrokes'],
    surface: ['Low-friction fabric', 'Smooth fabric', 'Recycled surface'],
    base: ['Non-slip rubber', 'Recycled natural rubber'],
    material: ['Recycled materials', 'Non-hazardous materials'],
    dimensions: ['220x180x3mm'],
    thickness: ['3mm'],
    wrist_support: ['Yes'],
    compatibility: ['Windows 7+', 'Mac OS'],
    color: ['Black', 'Gray'],
  },
  laptop_bags: {
    product_subtype: ['Backpack', 'Sleeve', 'Carrying case', 'Luggage'],
    laptop_size: ['11.6"', '14"', '15.6"', '16"', '17"', '18"', '22"'],
    capacity: ['25L', '25L + 2.5L'],
    carry_style: ['Backpack', 'Sleeve', 'Briefcase', '3-in-1', 'Luggage'],
    material: ['rPET', 'Synthetic fabric', 'Durable fabric', 'PU leather', 'Aluminum alloy'],
    water_resistant: ['Yes'],
    compartments: ['Laptop compartment', 'Front pocket', 'Organizer', 'Power adapter sleeve', 'Multiple compartments'],
    features: ['TSA lock', 'Detachable hanger', 'Silent wheels', 'Trolley strap', 'Reinforced base', 'Antimicrobial material', 'Detachable crossbody bag'],
    weight: ['0.4kg', '0.6kg'],
    color: ['Black', 'Gray', 'Green'],
  },
  headsets: {
    product_subtype: ['Headset', 'Gaming headset', 'Earbuds', 'Conference headset', 'Office headset'],
    connection: ['Wired USB-A', '3.5mm audio', 'USB + 3.5mm audio', '2.4GHz Wireless + Bluetooth 5.2', 'Bluetooth 5.3'],
    connector: ['USB-A', 'USB-C', '3.5mm audio jack'],
    driver_size: ['8mm', '30mm', '50mm'],
    sound: ['Stereo', '7.1 surround'],
    microphone: ['Built-in microphone', 'Detachable microphone', 'Detachable omnidirectional microphone', 'Omnidirectional microphone', 'Flexible boom microphone', 'ENC microphone'],
    frequency_response: ['20Hz-20kHz'],
    impedance: ['21 ohm', '32 ohm'],
    sensitivity: ['105dB', '115dB'],
    battery_life: ['4 hours', '12 hours', '14 hours with case', '240 minutes'],
    charging_time: ['2.5 hours'],
    wireless_range: ['10m'],
    lighting: ['RGB', 'Multicolor RGB'],
    controls: ['Touch controls', 'In-line control', 'USB control box'],
    design: ['In-ear', 'Over-ear', 'Adjustable headband', 'Soft foam ear pads'],
    cable_length: ['1200mm', '1450mm', '2m'],
    weight: ['160g'],
    color: ['Black'],
  },
  keyboards: {
    product_subtype: ['Gaming keyboard'],
    layout: ['80%'],
    switch_type: ['Membrane'],
    numeric_keypad: ['No'],
    anti_ghosting: ['19-key'],
    lighting: ['Three-zone RGB'],
    keystroke_life: ['5 million keystrokes'],
    connection: ['Wired'],
  },
  controllers: {
    product_subtype: ['Gaming controller', 'Mobile gaming controller'],
    connection: ['Bluetooth 5.0', 'USB-C'],
    platform_compatibility: ['Windows', 'Android', 'iPhone 15 series', 'Android 9.0+'],
    vibration: ['Dual vibration motors'],
    sensors: ['Motion sensor'],
    buttons: ['15 buttons'],
    triggers: ['Analog triggers'],
    features: ['Turbo button', 'Interchangeable joysticks', 'Foldable design', 'LED indicators'],
    charging: ['18W fast charging'],
    phone_fit: ['Up to 21.08cm'],
    weight: ['114.8g'],
  },
  docking_stations: {
    product_subtype: ['Docking station', 'Docking stand', 'Laptop stand with hub', 'USB-C dongle'],
    host_connection: ['USB-C'],
    video_outputs: ['HDMI', 'DisplayPort', 'VGA', '2 x HDMI + DP'],
    max_displays: ['3'],
    usb_ports: ['4 x USB-A + 2 x USB-C', '3 x USB-A + USB-C', '3 x USB 3.0'],
    ethernet: ['RJ45', 'Gigabit Ethernet'],
    power_delivery: ['60W', '100W'],
    card_reader: ['SD/TF'],
    audio: ['3.5mm audio'],
    compatibility: ['Chromebook', 'Windows', 'Mac OS', 'Android', 'Linux', 'Chrome'],
    laptop_size: ['11.6"-15.6"'],
    material: ['Aluminum alloy'],
  },
  connectivity: {
    product_subtype: ['5G mobile hotspot', '5G dongle', '5G router', 'Wi-Fi mesh router', 'USB-C dongle'],
    wireless_standard: ['Wi-Fi 6', 'Wi-Fi 6E', 'Wi-Fi 7'],
    cellular: ['5G', '5G SA/NSA'],
    max_speed: ['2.7Gbps', '3.5Gbps', '5Gbps data transfer'],
    users: ['16 devices', '20 devices', '32 devices', '128 devices', '256 concurrent capable'],
    sim_support: ['Nano SIM', 'SIM + eSIM + vSIM', 'vSIM', 'TRI-SIM'],
    ethernet: ['Ethernet', 'WAN', 'RJ45'],
    usb: ['USB-C', 'USB 3.1 Type-C', '2 x USB 3.2 + 2 x USB 2.0'],
    video_outputs: ['2 x HDMI + DP'],
    battery: ['6460mAh', '6500mAh', '8000mAh', 'Up to 28 hours'],
    security: ['WPA3', 'VPN', 'Trend Micro Home Network Security'],
    ruggedness: ['MIL-STD-810H', 'IP54', 'IP68'],
    ports: ['SD/TF', '2 x HDMI', 'DisplayPort', 'RJ45', '3.5mm audio'],
    pack_size: ['Single pack', 'Dual pack', 'Triple pack'],
    qos: ['Hybrid QoS', 'Intel Killer Prioritization Engine'],
  },
  storage: {
    product_subtype: ['External SSD', 'Internal SSD'],
    capacity: ['1TB', '2TB', '4TB'],
    interface: ['USB 3.2 Gen2x2 Type-C', 'PCIe Gen5x4 NVMe'],
    read_speed: ['2000MB/s', '14000MB/s'],
    write_speed: ['2000MB/s', '13000MB/s'],
    form_factor: ['Portable', 'M.2'],
    heatsink: ['Active heatsink + fan'],
    dram_cache: ['2GB', '4GB'],
    endurance: ['1600TBW', '3200TBW'],
    iops: ['2000K / 1600K IOPS'],
    lighting: ['RGB'],
    compatibility: ['Multi-platform'],
  },
  graphics_cards: {
    product_subtype: ['Graphics card'],
    gpu_model: ['Intel Arc A750', 'Intel Arc B570', 'Radeon RX 9060 XT', 'Radeon RX 9070', 'Radeon RX 9070 XT'],
    architecture: ['Intel Xe', 'AMD RDNA 4'],
    memory: ['8GB GDDR6', '10GB GDDR6', '16GB GDDR6'],
    memory_bandwidth: ['640GB/s'],
    gpu_clock: ['2.2GHz'],
    board_power: ['250W', '340W'],
    interface: ['PCIe 5.0 x16'],
    max_resolution: ['8K', '7680x4320'],
    display_support: ['Up to 4 displays'],
    ports: ['HDMI 2.0 + 3 x DisplayPort 2.0', 'HDMI 2.1 + DisplayPort 2.1', '3 x DisplayPort 2.1 + 1 x HDMI 2.1a', '2 x DisplayPort 2.1 + 1 x HDMI 2.1a'],
    cooling: ['Hybrid cooling + vapor chamber', 'FrostBlade cooling', 'Triple FrostBlade 4.0 + vapor chamber', 'Dual FrostBlade fans'],
    upscaling: ['XeSS', 'FidelityFX Super Resolution 4'],
    ray_tracing: ['Yes'],
    color: ['Black', 'White'],
  },
  projectors: {
    product_subtype: ['Projector'],
    resolution: ['SVGA 800x600', 'XGA 1024x768', 'WXGA 1280x800', 'HD 1280x720', 'FWVGA 854x480', 'FHD 1920x1080', '4K UHD 3840x2160'],
    contrast_ratio: ['1000:1', '5000:1', '10000:1', '13000:1', '20000:1', '50000:1', '2000000:1'],
    aspect_ratio: ['4:3', '16:9', '16:10'],
    throw_ratio: ['1.12-1.47', '1.15-1.5', '1.3', '1.4', '1.49-1.64', '1.5-1.66', '1.54-1.72', '1.55-1.70', '1.94-2.16', '1.96-2.15'],
    brightness: ['100 lm', '135 ANSI lm', '500 ANSI lm', '800 ANSI lm', '2700 ANSI lm', '3200 ANSI lm', '4000 ANSI lm', '4500 ANSI lm', '4800 ANSI lm', '5000 ANSI lm', '5500 ANSI lm'],
    lamp_life: ['5000h / 10000h', '20000h / 30000h', '30000h', '50000h'],
    battery: ['5200mAh'],
    wireless_projection: ['Yes'],
    speaker: ['Bluetooth speaker'],
    durability: ['IP6X', '24/7 operation'],
    color: ['Black', 'White', 'Blue'],
  },
  audio: {
    product_subtype: ['Soundbar'],
    connection: ['USB'],
    sound: ['2.0 stereo'],
    size: ['16.5"'],
    power: ['USB-powered'],
    lighting: ['RGB'],
    platform_compatibility: ['Windows', 'Android'],
  },
  cameras: {
    product_subtype: ['3D camera'],
    resolution: ['8MP per eye'],
    aperture: ['f/2.0'],
    focal_length: ['3.0mm'],
    field_of_view: ['80 degrees'],
    display: ['2.41" touchscreen'],
    focus: ['Auto focus', 'Touch focus'],
    stabilization: ['EIS', '6-axis gyroscopic stabilization', 'IMU stabilization'],
    streaming: ['YouTube 3D', 'Teams', 'Zoom', 'Google Meet'],
    compatibility: ['Acer SpatialLabs', 'Apple Vision Pro', 'VR/AR headsets', '3D projectors'],
    weather_resistant: ['Yes'],
  },
  electric_scooters: {
    product_subtype: ['Electric scooter'],
    max_speed: ['20km/h'],
    range: ['35km'],
    charging_time: ['4 hours'],
    brakes: ['Front and rear disc brakes'],
    suspension: ['Front and rear suspension'],
    motor: ['48V / 350W hub motor'],
  },
  gaming_chairs: {
    product_subtype: ['Gaming chair'],
    backrest: ['90-160 degrees'],
    armrests: ['1D adjustable', '4D adjustable'],
    pillows: ['Head pillow', 'Head and back pillows'],
    max_load: ['170kg'],
    weight: ['19kg'],
  },
  gaming_consoles: {
    product_subtype: ['Handheld gaming console'],
    operating_system: ['Win 11 Home'],
    processor: ['AMD Ryzen 7 8840HS'],
    screen_size: ['7"'],
    resolution: ['1920x1080'],
    refresh_rate: ['144'],
    ram: ['16'],
    ram_type: ['LPDDR5X'],
    storage: ['1TB SSD'],
    gpu: ['Radeon 780M'],
  },
  gaming_desks: {
    product_subtype: ['Gaming desk'],
    lighting: ['RGB'],
    features: ['Headset hook', 'Drink holder', 'Cable cutouts'],
  },
  webcams: {
    product_subtype: ['Webcam'],
    resolution: ['FHD 1080p'],
    frame_rate: ['30fps'],
    field_of_view: ['80 degrees'],
    microphone: ['Noise-reducing microphone'],
    privacy_cover: ['Yes'],
    compatibility: ['Windows', 'Linux', 'Mac'],
  },
  ai_workstations: {
    product_subtype: ['AI mini workstation'],
    processor: ['NVIDIA Grace Blackwell GB10'],
    processor_cores: ['20'],
    ai_performance: ['1 PFLOP FP4'],
    memory: ['128GB LPDDR5X unified'],
    storage: ['4TB PCIe 4.0 NVMe SSD'],
    operating_system: ['NVIDIA DGX OS'],
    ethernet: ['10GbE RJ45'],
    ports: ['HDMI 2.1b', '4 x USB-C 3.2 Gen 2x2'],
    chassis_volume: ['1.2L'],
    dimensions: ['150x150x50.5mm'],
    weight: ['1.2kg'],
    power_adapter: ['240W'],
    model_size: ['Up to 200B parameters', 'Up to 405B parameters with two units'],
  },
  desktops: {
    product_subtype: ['Desktop', 'Gaming desktop', 'All-in-one desktop', 'Mini desktop', 'Chromebox'],
    series: ['Predator Orion', 'Nitro', 'Aspire C', 'Aspire XC', 'Veriton', 'Chromebox'],
    operating_system: ['Win 11 Home', 'Win 11 Pro', 'ChromeOS'],
    processor_brand: ['Intel', 'AMD'],
    processor: ['Core i5', 'Core i7', 'Core Ultra 5', 'Core Ultra 7', 'Core Ultra 9', 'AMD Ryzen 3', 'AMD Ryzen 5'],
    processor_model: ['i5-1235U', 'i5-12450H', 'i5-14400', 'i7-13700T', 'i7-14700', 'i7-14700T', 'Core Ultra 5 125U', 'Core Ultra 5 225', 'Core Ultra 7 155U', 'Core Ultra 7 265', 'Core Ultra 7 265F', 'Core Ultra 7 265KF', 'Core Ultra 9 285K', 'Ryzen 3 7320U', 'Ryzen 5 7520U'],
    processor_cores: ['10', '16', '20'],
    ram: ['8', '16', '32', '64'],
    ram_type: ['DDR4', 'DDR5', 'LPDDR5'],
    storage: ['256GB SSD', '512GB SSD', '1TB SSD', '2TB SSD', '4TB SSD', '1TB SSD + 2TB HDD', '2 x 1TB SSD'],
    storage_type: ['SSD', 'SSD + HDD'],
    gpu: ['Intel UHD Graphics', 'Intel HD Graphics', 'Intel Iris Xe', 'Intel Graphics', 'AMD Radeon Graphics', 'RTX 5060', 'RTX 5080', 'RTX 5090'],
    gpu_memory: ['8GB', '16GB', '32GB', 'Shared'],
    screen_size: ['23.8', '27'],
    resolution: ['1920x1080'],
    aspect_ratio: ['16:9'],
    keyboard_mouse: ['Included', 'Not included'],
    color: ['Black', 'Silver', 'White'],
  },
}

const BRAND_KEYWORDS: Record<AttributeBrand, string[]> = {
  acer: ['aspire', 'swift', 'travelmate', 'nitro', 'acer'],
  predator: ['predator', 'helios', 'triton', 'xb', 'x27u', 'x32', 'x34', 'z57'],
}

export function getAttributeOptions(
  collection: AttributeCollection,
  brand?: AttributeBrand
): AttributeOptionsMap {
  const base = ATTRIBUTE_OPTIONS[collection]
  if (!brand) return base

  const brandName = brand === 'acer' ? 'Acer' : 'Predator'
  const keywords = BRAND_KEYWORDS[brand]
  const seriesValues = (base.series ?? []).filter((value) => {
    const lower = value.toLowerCase()
    if (lower === brand.toLowerCase()) return true
    if (lower.includes(brandName.toLowerCase())) return true
    return keywords.some((kw) => lower.includes(kw))
  })

  return {
    ...base,
    brand: [brandName],
    ...(seriesValues.length > 0 ? { series: seriesValues } : {}),
  }
}
